# 車輪的順序 (四輪對應索引)
# FL: Front Left, FR: Front Right, RL: Rear Left, RR: Rear Right
wheel_order: [FL, FR, RL, RR]

# 搖桿按鈕映射 (暫時都設 0.0，代表無作用)
# 每個按鈕對應四個輪子的速度輸出，可在需要時自訂
buttons:
  A:      [0.0, 0.0, 0.0, 0.0]
  B:      [0.0, 0.0, 0.0, 0.0]
  X:      [0.0, 0.0, 0.0, 0.0]
  Y:      [0.0, 0.0, 0.0, 0.0]
  RB:     [0.0, 0.0, 0.0, 0.0]   # Right bumper
  LB:     [0.0, 0.0, 0.0, 0.0]   # Left bumper
  Start:  [0.0, 0.0, 0.0, 0.0]
  Back:   [0.0, 0.0, 0.0, 0.0]
  LStick: [0.0, 0.0, 0.0, 0.0]   # 左搖桿按壓
  BTN13: [0.0, 0.0, 0.0, 0.0]

# 機械手臂關節角度配置 (角度以度為單位，發布時會轉換為弧度)
robot_arm_joints:
  A:      [130.0, 10.0, 160.0]    # A鍵：預設位置1 (5軸角度)
  Y:      [0.0, 110.0, 60.0] # Y鍵：預設位置2 (5軸角度)

# 機械手臂手動控制設定
robot_arm_control:
  ay_axis_initial_angle: 0.0  # AY最後一軸的初始角度
  angle_increment: 10.0         # 按B鍵時增加的角度
  angle_decrement: -10.0        # 按X鍵時減少的角度d
  ay_axis_max_angle: 90.0       # AY軸的最大角度
  ay_axis_min_angle: 0.0      # AY軸的最小角度

# 搖桿角度映射 (角度區間 → 車輪速度)
axes_angle_map:
  left_stick:
    deadzone: 0.15   # 搖桿中心死區 (避免手抖造成誤動作)
    rules:
      # 右轉區域 (角度 -30° ~ 30°)
      - range: [-30.0, 30.0]
        speed: [30.0, -30.0, 30.0, -30.0]  # 左右輪相反，讓車子右轉

      # 前進區域 (角度 31° ~ 130°)
      - range: [31.0, 130.0]
        speed: [30.0, 30.0, 30.0, 30.0]    # 四輪同方向，讓車子前進

      # 左轉區域 (角度 140° ~ 200°)
      - range: [140.0, 200.0]
        speed: [-30.0, 30.0, -30.0, 30.0]  # 左右輪相反，讓車子左轉

      # 後退區域 (角度 210° ~ 300°)
      - range: [210.0, 300.0]
        speed: [-30.0, -30.0, -30.0, -30.0]  # 四輪同方向，讓車子後退

  right_stick:
    deadzone: 0.15   # 搖桿中心死區 (避免手抖造成誤動作)
    rules:
      # 右轉區域 (角度 -30° ~ 30°)
      - range: [-30.0, 30.0]
        speed: [30.0, -30.0, 30.0, -30.0]  # 左右輪相反，讓車子右轉

      # 前進區域 (角度 31° ~ 130°)
      - range: [31.0, 130.0]
        speed: [30.0, 30.0, 30.0, 30.0]    # 四輪同方向，讓車子前進

      # 左轉區域 (角度 140° ~ 200°)
      - range: [140.0, 200.0]
        speed: [-30.0, 30.0, -30.0, 30.0]  # 左右輪相反，讓車子左轉

      # 後退區域 (角度 210° ~ 300°)
      - range: [210.0, 300.0]
        speed: [-30.0, -30.0, -30.0, -30.0]  # 四輪同方向，讓車子後退

# ROSBridge 設定
rosbridge:
  host: 127.0.0.1   # ROSBridge 伺服器 IP (本機)
  port: 9090        # ROSBridge 連線 port

# ROS Topic 映射設定
# 每個 topic 綁定車輪索引，將對應速度值送到指定 topic
ros_topics:
  - name: /car_C_front_wheel
    indices: [0, 1]   # 綁定前輪 (FL, FR)
  - name: /car_C_rear_wheel
    indices: [0,1, 2, 3]   # 綁定後輪 (RL, RR)

# 機械手臂 ROS Topic 設定
robot_arm_topic:
  name: /robot_arm
  msg_type: trajectory_msgs/JointTrajectoryPoint